# Generated by Django 2.1.15 on 2021-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetIndexDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField()),
                ('rating', models.TextField()),
                ('aum', models.TextField()),
                ('fund_return_1yr', models.TextField()),
                ('fund_return_2yr', models.TextField()),
                ('fund_return_3yr', models.TextField()),
                ('fund_return_5yr', models.TextField()),
                ('fund_return_10yr', models.TextField()),
                ('volatility', models.TextField()),
                ('unique_fund_id', models.TextField()),
            ],
        ),
    ]
